//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESLTestProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class response
    {
        public response()
        {
            this.response_value = "";
            this.response_outcome = 0;
        }
    
        public int response_id { get; internal set; }
        public string response_parameter { get; set; }
        public byte[] response_raw { get; set; }
        public string response_value { get; set; }
        public int response_run_id { get; set; }
        public short response_outcome { get; set; }
        public short response_report_column { get; set; }
    
        public virtual run run { get; set; }
    }
}
