//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESLTestProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class run
    {
        public run()
        {
            this.responses = new HashSet<response>();
        }
    
        public int run_id { get; internal set; }
        public System.DateTime run_start_timestamp { get; set; }
        public System.DateTime run_complete_timestamp { get; set; }
        public bool run_complete { get; set; }
    
        public virtual session session { get; set; }
        public virtual ICollection<response> responses { get; set; }
        public virtual pcb_unit pcb_unit { get; set; }
    }
}
