//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESLTesProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class pcb_unit
    {
        public pcb_unit()
        {
            this.runs = new HashSet<run>();
        }
    
        public int pcb_unit_id { get; internal set; }
        public string pcb_unit_serial_number { get; set; }
        public string pcb_unit_serial_sticker_manufacture { get; set; }
        public string pcb_unit_serial_sticker_test { get; set; }
    
        public virtual ICollection<run> runs { get; set; }
    }
}
