//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESLTesProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        public int session_id { get; internal set; }
        public string session_time_stamp { get; set; }
        public string session_user_id { get; set; }
    }
}
