//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESLTesProcess.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class technician
    {
        public technician()
        {
            this.sessions = new HashSet<session>();
        }
    
        public int technicain_id { get; internal set; }
        public string technician_name { get; set; }
        public string technician_create_timestamp { get; set; }
    
        public virtual ICollection<session> sessions { get; set; }
    }
}
